const pool = require('../../../config/database');

exports.migrate = async () => {
  await pool.query(`
    CREATE TABLE IF NOT EXISTS category_galleries (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name varchar(255)
    )
  `);

  await pool.query(`
    CREATE TABLE IF NOT EXISTS galleries (
      id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      category_galleries_id int NOT NULL,
      slug text UNIQUE NOT NULL,
      title varchar(255) NOT NULL,
      image varchar(255) NOT NULL,
      snippet text,
      author varchar(100) NOT NULL,
      created_at timestamp NOT NULL DEFAULT (now()),
      updated_at timestamp NOT NULL DEFAULT (now()),
      deleted_at timestamp
    )
  `);
};
