name: Run Tests and Coverage on Pull Request (PR)

on:
  pull_request:
    branches:
      - main
      - testing
      - testing-ci
  pull_request_target:
    types:
      - assigned
      - labeled
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - edited

jobs:
  validate:
    name: Validate PR Title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Validate PR
        id: validate
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET_TOKEN }}
        with:
          types: |
            build
            chore
            ci
            docs
            feat
            fix
            perf
            refactor
            revert
            style
            test
          requireScope: false
          subjectPattern: "^[A-Z].*$"
          subjectPatternError: "The subject of the PR title must start with a capital letter."
        continue-on-error: true
      - name: Comment PR
        if: steps.validate.outcome == 'failure'
        uses: actions/github-script@v5
        with:
          github-token: ${{secrets.SECRET_TOKEN}}
          script: |
            const issue_number = context.payload.pull_request.number;
            const message = 'Validasi gagal! Judul PR harus dimulai dengan huruf kapital dan mengikuti format "type(scope): Subject".';
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: message
            });

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npm test
      - name: Jest Coverage Report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          github-token: ${{ secrets.SECRET_TOKEN }}
